# Generated by Django 5.2.7 on 2025-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('quality', models.CharField(max_length=50)),
                ('release', models.IntegerField()),
                ('rating', models.FloatField()),
                ('category', models.IntegerField()),
                ('link', models.URLField()),
                ('imgUrl', models.URLField()),
            ],
        ),
    ]
